In [1]:
import numpy as np

# create a sample dataset with 5 samples
X = np.array([[35, 12, 50000],
              [25, 16, 60000],
              [40, 14, 70000],
              [30, 12, 55000],
              [45, 18, 80000]])

# calculate the mean vector
mean_X = np.mean(X, axis=0)

# subtract the mean from X
X_centered = X - mean_X

# calculate the covariance matrix
cov_X = 1/(X.shape[0]-1) * X_centered.T.dot(X_centered)

# print the covariance matrix
print(cov_X)


[[6.250e+01 7.500e+00 6.875e+04]
 [7.500e+00 6.800e+00 2.600e+04]
 [6.875e+04 2.600e+04 1.450e+08]]
